In [7]:
#импортируем нужные библиотеки
import numpy
import matplotlib.pyplot as plt
%matplotlib inline
#Вычисляем функцию, которая вернет результат вычисления функции
def xfunct(x):
    return numpy.sin(x/5)*numpy.exp(x/10)+5*numpy.exp(-x/2)

In [8]:
#Решаем первую задачу: Сформируйте систему линейных уравнений
m1 = numpy.array([[1,1],[1,15]])
v1 = numpy.array([xfunct(1), xfunct(15)])
result = numpy.linalg.solve(m1,v1)
result

array([ 3.43914511, -0.18692825])

In [9]:
#Решаем вторую задачу
w2_m1 = numpy.array([
                        [1, 1,  (1**2)],
                        [1, 8,  (8**2)],
                        [1, 15, (15**2)]
                    ])
w2_v1  = numpy.array([xfunct(1), xfunct(8), xfunct(15)])
result = numpy.linalg.solve(w2_m1,w2_v1)
print(result)

[ 3.32512949 -0.06531159 -0.00760104]


In [10]:
#Решаем третью задачу
w3_m1 = numpy.array([
                     [1, 1,  (1**2),  (1**3)],
                     [1, 4,  (4**2),  (4**3)],
                     [1, 10, (10**2), (10**3)],
                     [1, 15, (15**2), (15**3)]
                    ])

w3_v1 = numpy.array([xfunct(1), xfunct(4), xfunct(10), xfunct(15)])
result = numpy.linalg.solve(w3_m1,w3_v1)
print(result)

[ 4.36264154 -1.29552587  0.19333685 -0.00823565]


In [11]:
#Cохраняем результат в файл:
f1 = open('submission-2.txt','w')
str = (f'{round(result[0],2)} {round(result[1],2)} {round(result[2],2)} {round(result[3],2)}')
f1.write(str)
print(str)
f1.close();

4.36 -1.3 0.19 -0.01
